#### icon
# nf-ple-left_half_circle_thick
# nf-pl-left_hard_divider
# nf-pl-left_hard_divider
# nf-pl-right_hard_divider
# nf-ple-right_half_circle_thick

format = """
[╭─](fg:#444444)\
$os\
[ ](fg:white bg:blue)\
$directory\
$git_branch\
$git_status\
$git_metrics\
[](fg:blue)\
$fill\
[](fg:yellow)\
$status\
$cmd_duration\
[](fg:white bg:yellow)\
$time\
\n$character\
"""

right_format = """
$lua
$rust
$shell
"""

[os]
format = "[$symbol]($style)"
style = 'fg:black bg:white'
disabled = false

[os.symbols]
Windows = " 󰍲 "
Ubuntu = " 󰕈 "
SUSE = "  "
Raspbian = " 󰐿 "
Mint = " 󰣭 "
Macos = " 󰀵 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = "  "
Artix = "  "
CentOS = "   "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "

[directory]
truncation_length = 6
truncation_symbol = '  ' # nf-fa-folder_open
truncate_to_repo = false
home_symbol = ' ~ ' # nf-fa-home
style = 'fg:#FFFFFF bg:blue'
read_only = ' 󰌾 ' # nf-md-lock
read_only_style = 'fg:red bg:blue'
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = '  ' # nf-fa-github_alt, nf-fa-code_fork
truncation_length = 4
truncation_symbol = ''
style = 'fg:#FFFFFF bg:blue'
format = '[  $symbol$branch(:$remote_branch)]($style)' # nf-pl-left_soft_divider

[git_status]
style = 'fg:#FFFFFF bg:blue'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = '([\[$all_status$ahead_behind\]]($style))'

[git_metrics]
added_style = 'fg:#00FF00 bg:blue'
deleted_style = 'fg:#FF0000 bg:blue'
format = '[+$added]($added_style)[/-$deleted ]($deleted_style)'
disabled = false

[fill]
symbol = '─'
style = '#444444'

[character]
format = '[╰─ ](#444444)'

[cmd_duration]
min_time = 1
style = 'fg:black bg:yellow'
format = "[ $duration  ]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[status]
disabled = false
format = '[ $status ✘ ](fg:red bg:yellow)'

[time]
disabled = false
style = 'fg:black bg:white'
format = '[ $time  ]($style) ' # nf-pl-right_soft_divider, nf-fa-clock_o
utc_time_offset = '+9'

[shell]
disabled = false
bash_indicator = '[    BSH-MODE](aqua)'
zsh_indicator = '[    ZSH-MODE](fuchsia)'
nu_indicator = '[    NSH-MODE](blue)'
fish_indicator = '[    FSH-MODE](yellow)'
elvish_indicator = '[    ESH-MODE](lime)'
xonsh_indicator = '[    XSH-MODE](red)'

[lua]
symbol = "" # nf-seti-lua
format = '[  $symbol $version ](blue)' # nf-pl-right_soft_divider

[rust]
symbol = "" # nf-dev-rust
format = '[  $symbol $version ](red)' # nf-pl-right_soft_divider
